Auction/Web/Auction.Web/Controllers/ItemController.cs
namespace Auction.Web.Controllers
{
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using Auction.Data.Repositories;
    using Auction.Infrastructure.Mapping;
    using Auction.Models;
    using Auction.Services.Data;
    using Auction.Web.ViewModels.Item;

    public class ItemController : Controller
    {
        private IDbRepository<Auction> dataAuction;
        private IDbRepository<Item> dataItem;
        private IDbRepository<User> dataUser;
        private IDbRepository<Image> dataImage;

        public ItemController(IDbRepository<Auction> auctions,
            IDbRepository<Item> items,
            IDbRepository<User> users,
            IAuctionService service,
            IDbRepository<Image> images)
        {
            this.dataAuction = auctions;
            this.dataItem = items;
            this.dataUser = users;
            this.dataImage = images;
        }

        [HttpGet]
        public ActionResult ListAllItems()
        {
            IQueryable<ItemViewModel> items = this.dataItem.All().OrderBy(x => x.Id).To<ItemViewModel>();
            return this.View(items);
        }

        public ActionResult Edit(int id)
        {
            return Content("Edit motherfucker");
        }

        [HttpGet]
        public ActionResult CreateItem()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateItem(CreateItemViewModel model, IEnumerable<HttpPostedFileBase> files)
        {
            foreach (var file in files)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var image = new Image
                                    {
                                        FileName = Path.GetFileName(file.FileName),
                                        Extension = Path.GetExtension(file.FileName),
                                        ContentType = file.ContentType,
                                        ContentLength = file.ContentLength,
                                    };

                    using (var reader = new BinaryReader(file.InputStream))
                    {
                        image.ImageArray = reader.ReadBytes(file.ContentLength);
                    }

                    model.Images.Add(image);
                }
            }

            if (ModelState.IsValid)
            {
                var item = new Item
                {
                    Title = model.Title,
                    Type = model.Type,
                    Author = model.Author,
                    Description = model.Description,
                    Images = model.Images
                };

                this.dataItem.Add(item);
                this.dataItem.Save();

                return this.RedirectToAction("Index", "Home");
            }

            return View(model);
        }
    }
}

Auction/Web/Auction.Web/Controllers/UsersController.cs
namespace Auction.Web.Controllers
{
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Mvc;
    using Auction.Data.Repositories;
    using Auction.Models;
    using Auction.Web.ViewModels.User;

    public class UsersController : BaseController
    {
        private IDbRepository<Auction> dataAuction;
        private IDbRepository<Item> dataItem;
        private IDbRepository<User> dataUser;

        public UsersController(IDbRepository<Auction> auctions, IDbRepository<Item> items, IDbRepository<User> users)
        {
            this.dataAuction = auctions;
            this.dataItem = items;
            this.dataUser = users;
        }

        [HttpGet]
        [Authorize]
        public ActionResult CurrentUserDetails()
        {
            var currentUserName = this.User.Identity.Name;

            this.CurrentUser = this.dataUser.All()
                .Where(u => u.UserName == currentUserName)
                .Select(UserViewModel.FromUser)
                .FirstOrDefault();

            return View(this.CurrentUser);
        }

        [Authorize]
        public ActionResult UserDetailsById(string id)
        {


            if (!Request.IsAjaxRequest())
            {
                Response.StatusCode = (int)HttpStatusCode.Forbidden;
                return this.Content("This action can be invoke only by AJAX call");
            }

            var user =
                this.dataUser.All()
                .Where(u => u.Id == id)
                .Select(UserViewModel.FromUser)
                .FirstOrDefault();

            if (user == null)
            {
                Response.StatusCode = (int)HttpStatusCode.NotFound;
                return this.Content("User not found");
            }

            string userInfo = string.Format(
                "Username: {0}, Id: {1}, Phone number: {2}",
                user.UserName,
                user.Id,
                user.PhoneNumber);

            return this.Content(userInfo);
        }

        [Authorize]
        public ActionResult Search(string query)
        {
            var result = this.dataUser.All()
                .Where(u => u.UserName.ToLower().Contains(query.ToLower()))
                .Select(UserViewModel.FromUser)
                .ToList();

            return this.PartialView("_UsersSearchResults", result);
        }

        [Authorize]
        //  [OutputCache(Duration = 15 * 60)] // cache the result
        public ActionResult AllUsers()
        {
            var allUsers = this.dataUser.All()
                .Select(UserViewModel.FromUser).OrderBy(u => u.UserName).ToList();
            return View(allUsers);
        }

        public JsonResult AllUsersAsJson()
        {
            var users = this.dataUser.All().OrderBy(n => n.UserName)
                .Select(UserViewModel.FromUser).ToList();

            return this.Json(users, JsonRequestBehavior.AllowGet);
        }

        
        [HttpPost]
        public ActionResult CurrentUserDetails(HttpPostedFileBase file)
        {
            var path = Path.Combine(Server.MapPath("~/Content/Images/Avatars/"), file.FileName);
            
            var data = new byte[file.ContentLength];
            file.InputStream.Read(data, 0, file.ContentLength);
            using (var sw = new FileStream(path, FileMode.Create))
            {
                sw.Write(data, 0, data.Length);
            }

            var currentUserName = this.User.Identity.Name;

            var currentUser = this.dataUser.All()
                .FirstOrDefault(u => u.UserName == currentUserName);

            currentUser.AvatarFileName = file.FileName;
            this.dataUser.Save();

            this.CurrentUser =
                this.dataUser.All()
                    .Where(u => u.UserName == currentUserName)
                    .Select(UserViewModel.FromUser)
                    .FirstOrDefault();


            return View(this.CurrentUser);
        }

        public FileResult GetImage(string filename)
        {
            var currentUserName = this.User.Identity.Name;

            this.CurrentUser =
                this.dataUser.All()
                    .Where(u => u.UserName == currentUserName)
                    .Select(UserViewModel.FromUser)
                    .FirstOrDefault();

            var path = Path.Combine(Server.MapPath("~/Content/Images/Avatars/"), filename);

            return File(path, "image/jpeg");

            /*byte[] fileBytes = System.IO.File.ReadAllBytes(path);
            string fileName = System.IO.Path.GetFileName(path);
            string extension = System.IO.Path.GetExtension(path);
            return File(fileBytes, extension, fileName);*/
        }

    }
}

Auction/Web/Auction.Web/Views/Shared/_ChatHistory.cshtml
@model ICollection<global::Auction.Web.ViewModels.Bid.BidDetailsViewModel>

@foreach (var message in Model)
{
    if (message.Bidder != null && message.Winner != null)
    {
        var receivers = String.Join(", ", message.Bidders.Select(u => u.UserName));
        <li class="list-group-item">
            <div class="well well-sm">
                <p>
                    <strong>@message.CreatedOn</strong>
                </p>

                <p>
                    <strong>from @message.Bidder.UserName to @receivers</strong>
                </p>
                <p>
                    <strong>@message.Winner.UserName</strong>
                </p>
                <p>
                    <strong>@message.Value</strong>
                </p>
                <p>
                    <strong>@message.CurrentPrice</strong>
                </p>
            </div>
        </li>
    }
}

Auction/Web/Auction.Web/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

Auction/Web/Auction.Web/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

Auction/Web/Auction.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Live Auction</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery.signalR-2.2.0.js"></script>
    <script src="~/signalr/hubs" type="text/javascript"></script>
    @Scripts.Render("~/bundles/jquery.unobtrusive-ajax")
    @RenderSection("styles", required: false)

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Live Auction", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Home<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new{})</li>
                            <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { })</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { })</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Users<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("User Details", "CurrentUserDetails", "Users", new { area = "Admin" }, new { })</li>
                            <li>@Html.ActionLink("All Users", "AllUsers", "Users", new { area = "Admin" }, new { })</li>
                        </ul>
                    </li>

                    <li>@Html.ActionLink("All Auctions", "ListAllAuctions", "PublicAuction", new { area = "" }, new { })</li>
                    <li>@Html.ActionLink("All Items", "ListAllItems", "PublicItem", new { area = "" }, new { })</li>
                    <li>@Html.ActionLink("Join To Active Auction", "JoinToAuction", "Bid", new { area = "" }, new { })</li>

                    @if (this.User.IsInRole("Admin"))
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin Area<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Create Auction", "CreateAuction", "Auction", new { area = "Admin" }, new { })</li>
                                <li>@Html.ActionLink("Create Item", "CreateItem", "Item", new { area = "Admin" }, new { })</li>
                                <li>@Html.ActionLink("Activate Auction", "SetActiveAuction", "Auction", new { area = "Admin" }, new { })</li>
                            </ul>
                        </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Live Auction</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @*<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>*@
    @RenderSection("scripts", required: false)
</body>
</html>

Auction/Web/Auction.Web/Views/Shared/_LayoutGridMvc.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles {
    @Styles.Render("~/Content/gridmvc")
}

@RenderBody()

@section Scripts{
    @Scripts.Render("~/bundles/gridmvc")
}