Auction/Web/Auction.Web/ViewModels/Auction/AuctionDetailsViewModel.cs
namespace Auction.Web.ViewModels.Auction
{
    using System;
    using System.Collections.Generic;
    using global::Auction.Infrastructure.Mapping;
    using global::Auction.Models;

    public class AuctionDetailsViewModel : IMapFrom<Auction>
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public bool Active { get; set; }

        public DateTime DateOfAuction { get; set; }

        public int InitialPrice { get; set; }

        public int BidStep { get; set; }

        public ICollection<Item> Items { get; set; }
    }
}

Auction/Web/Auction.Web/Controllers/ItemController.cs
namespace Auction.Web.Controllers
{
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using Auction.Data.Repositories;
    using Auction.Infrastructure.Mapping;
    using Auction.Models;
    using Auction.Services.Data;
    using Auction.Web.ViewModels.Item;

    public class ItemController : Controller
    {
        private IDbRepository<Auction> dataAuction;
        private IDbRepository<Item> dataItem;
        private IDbRepository<User> dataUser;
        private IDbRepository<Image> dataImage;

        public ItemController(IDbRepository<Auction> auctions,
            IDbRepository<Item> items,
            IDbRepository<User> users,
            IAuctionService service,
            IDbRepository<Image> images)
        {
            this.dataAuction = auctions;
            this.dataItem = items;
            this.dataUser = users;
            this.dataImage = images;
        }

        [HttpGet]
        public ActionResult ListAllItems()
        {
            IQueryable<ItemViewModel> items = this.dataItem.All().OrderBy(x => x.Id).To<ItemViewModel>();
            return this.View(items);
        }

        public ActionResult Edit(int id)
        {
            return Content("Edit motherfucker");
        }

        [HttpGet]
        public ActionResult CreateItem()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateItem(CreateItemViewModel model, IEnumerable<HttpPostedFileBase> files)
        {
            foreach (var file in files)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var image = new Image
                                    {
                                        FileName = Path.GetFileName(file.FileName),
                                        Extension = Path.GetExtension(file.FileName),
                                        ContentType = file.ContentType,
                                        ContentLength = file.ContentLength,
                                    };

                    using (var reader = new BinaryReader(file.InputStream))
                    {
                        image.ImageArray = reader.ReadBytes(file.ContentLength);
                    }

                    model.Images.Add(image);
                }
            }

            if (ModelState.IsValid)
            {
                var item = new Item
                {
                    Title = model.Title,
                    Type = model.Type,
                    Author = model.Author,
                    Description = model.Description,
                    Images = model.Images
                };

                this.dataItem.Add(item);
                this.dataItem.Save();

                return this.RedirectToAction("Index", "Home");
            }

            return View(model);
        }
    }
}

Auction/Web/Auction.Web/Controllers/PublicAuctionController.cs
namespace Auction.Web.Controllers
{
    using System.Web.Mvc;
    using Auction.Services.Data;
    using Auction.Web.ViewModels.Auction;
    using Infrastructure.Mapping;

    public class PublicAuctionController : BaseController
    {
        private readonly IAuctionService service;

        public PublicAuctionController(IAuctionService service)
        {
            this.service = service;
        }

        public ActionResult ListAllAuctions()
        {
            var auctions = this.service.GetAllAuctions().To<AuctionViewModel>();

            return this.View(auctions);
        }

        [Authorize]
        public ActionResult AuctionDetails(int id)
        {
            var auction = this.service.GetById(id);
            var model = this.Mapper.Map<AuctionDetailsViewModel>(auction);

            return View(model);
        }
    }
}

Auction/Web/Auction.Web/Views/PublicAuction/AuctionDetails.cshtml
@model global::Auction.Web.ViewModels.Auction.AuctionDetailsViewModel
@{
    ViewBag.Title = "Auction Details";
}

<h2>@ViewBag.Title</h2>
<div class="row">
    <div class="col">
        
            <div class="col col-md-6">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong class="active">@Model.Name</strong> @Html.ActionLink("See details", "AuctionDetails", "PublicAuction", new { id = Model.Id }, new { @class = "btn btn-info btn-sm" })</h3>
                    </div>
                    <div class="panel-body">
                        <p class="alert-success">
                            @if (Model.Active)
                            {
                                @:Status: Active
                                }
                            else
                            {
                                @:Status: Not active
                                }
                        </p>
                        <p class="text-info">
                            Initial price: <b>@Model.InitialPrice $</b>
                        </p>
                        <p class="text-info">
                            Bid step: <b>@Model.BidStep $</b>
                        </p>
                        <p class="text-danger">
                            Date of auction: <b>@Model.DateOfAuction.ToShortDateString()</b>
                        </p>
                        <ul class="list-group">
                            @foreach (var item in Model.Items)
                            {
                                <li class="list-group-item" style="background-color: oldlace;">
                                    <p class="text-info">Item title: @item.Title @Html.ActionLink("See details", "ItemDetails", "PublicItem", new { id = item.Id }, new { @class = "btn btn-info btn-sm" })</p>
                                    <p class="text-info">Author: @item.Author</p>
                                    <p class="text-info">Type: @item.Type</p>
                                    <p class="text-info">Descritpion: @item.Description</p>
                                    <div class="row">
                                        @foreach (var image in item.Images)
                                        {
                                            <div class="col">
                                                <div class="col col-md-6 text-center">
                                                    <img src="@Url.Action("GetImage", "Item", new { id = image.Id })" width="200" alt="Item image" />
                                                </div>
                                            </div>
                                        }
                                    </div>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
    </div>
</div>

Auction/Web/Auction.Web/Views/PublicAuction/ListAllAuctions.cshtml
@model IEnumerable<global::Auction.Web.ViewModels.Auction.AuctionViewModel>

@{
    ViewBag.Title = "Auctions";
}

<h2>@ViewBag.Title</h2>

@if (TempData["Deactivated"] != null)
{
    <div class="alert alert-danger">
        @TempData["Deactivated"]
    </div>
}

@if (TempData["Success"] != null)
{
    <div class="row alert alert-success">
        @TempData["Success"]
    </div>
}

@Html.Grid(Model).Columns(columns =>
{

    columns.Add()
            .Encoded(false)
            .Sanitized(false)
            .SetWidth(200)
            .RenderValueAs(d =>
            @<b>
                @if (this.User.IsInRole("Admin"))
                {
                    @Html.ActionLink("Edit", "EditAuction", "Auction", new { id = d.Id, area = "Admin" }, new { @class = "btn btn-warning" })
                    <span></span>
                    @Html.ActionLink("Delete", "Delete", "Auction", new { id = d.Id, area = "Admin" }, new { @class = "btn btn-danger" })
                }
                 @Html.ActionLink("See details", "AuctionDetails", "PublicAuction", new { id = d.Id, area="" }, new { @class = "btn btn-info" })
            </b>);

    columns.Add(i => i.Name).Titled("Name").SetWidth(150);

    columns.Add(i => i.DateOfAuction).Titled("Date of auction").SetWidth(150);

    columns.Add(i => i.Active).Titled("Active").SetWidth(150);
    columns.Add(i => i.InitialPrice).Titled("Initial price").SetWidth(150);
    columns.Add(i => i.BidStep).Titled("Bid step").SetWidth(150);



}).WithPaging(5).Sortable().Filterable().WithMultipleFilters()