Auction/Web/Auction.Web/Controllers/ItemController.cs
namespace Auction.Web.Controllers
{
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using Auction.Data.Repositories;
    using Auction.Infrastructure.Mapping;
    using Auction.Models;
    using Auction.Services.Data;
    using Auction.Web.ViewModels.Item;

    public class ItemController : Controller
    {
        private IDbRepository<Auction> dataAuction;
        private IDbRepository<Item> dataItem;
        private IDbRepository<User> dataUser;
        private IDbRepository<Image> dataImage;

        public ItemController(IDbRepository<Auction> auctions,
            IDbRepository<Item> items,
            IDbRepository<User> users,
            IAuctionService service,
            IDbRepository<Image> images)
        {
            this.dataAuction = auctions;
            this.dataItem = items;
            this.dataUser = users;
            this.dataImage = images;
        }

        [HttpGet]
        public ActionResult ListAllItems()
        {
            IQueryable<ItemViewModel> items = this.dataItem.All().OrderBy(x => x.Id).To<ItemViewModel>();
            return this.View(items);
        }

        public ActionResult Edit(int id)
        {
            return Content("Edit motherfucker");
        }

        [HttpGet]
        public ActionResult CreateItem()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateItem(CreateItemViewModel model, IEnumerable<HttpPostedFileBase> files)
        {
            foreach (var file in files)
            {
                if (file != null && file.ContentLength > 0)
                {
                    var image = new Image
                                    {
                                        FileName = Path.GetFileName(file.FileName),
                                        Extension = Path.GetExtension(file.FileName),
                                        ContentType = file.ContentType,
                                        ContentLength = file.ContentLength,
                                    };

                    using (var reader = new BinaryReader(file.InputStream))
                    {
                        image.ImageArray = reader.ReadBytes(file.ContentLength);
                    }

                    model.Images.Add(image);
                }
            }

            if (ModelState.IsValid)
            {
                var item = new Item
                {
                    Title = model.Title,
                    Type = model.Type,
                    Author = model.Author,
                    Description = model.Description,
                    Images = model.Images
                };

                this.dataItem.Add(item);
                this.dataItem.Save();

                return this.RedirectToAction("Index", "Home");
            }

            return View(model);
        }
    }
}

Auction/Web/Auction.Web/Controllers/PublicItemController.cs
namespace Auction.Web.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using Auction.Data.Repositories;
    using Auction.Infrastructure.Mapping;
    using Auction.Models;
    using Auction.Web.ViewModels.Item;

    public class PublicItemController : BaseController
    {
        private IDbRepository<Item> dataItem;
        private IDbRepository<Image> dataImage;

        public PublicItemController(
            IDbRepository<Item> items,
            IDbRepository<Image> images)
        {
            this.dataItem = items;
            this.dataImage = images;
        }

        [HttpGet]
        public ActionResult ListAllItems()
        {
            IQueryable<ItemViewModel> items = this.dataItem.All().OrderBy(x => x.Id).To<ItemViewModel>();
            return this.View(items);
        }

        [HttpGet]
        public ActionResult ItemDetails(int id)
        {
            var item = this.dataItem.GetById(id);
            var viewModel = this.Mapper.Map<ItemViewModel>(item);

            return this.View(viewModel);
        }

        public FileResult GetImage(int id)
        {
            var image = this.dataImage.GetById(id);

            return new FileContentResult(image.ImageArray, image.ContentType);
        }
    }
}

Auction/Web/Auction.Web/Views/PublicItem/ItemDetails.cshtml
@model global::Auction.Web.ViewModels.Item.ItemViewModel
@{
    ViewBag.Title = "Item Details";
}

<h2>@ViewBag.Title</h2>

<div class="container">
    <div class="well">
        @Html.ActionLink("Back to items list", "ListAllItems", "PublicItem", new { @class = "btn btn-success btn-lg btn-block" })
    </div>

    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">@Model.Title</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col">
                    <div class="col-md-6">
                        <div class="well well-sm">
                            Author:
                            @Model.Author
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="well well-sm">
                            Item Type:
                            @Model.Type
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="well well-sm">
                            Description:
                            @Model.Description
                        </div>
                    </div>
                    <div class="col-md-12">
                        @foreach (var image in Model.Images)
                        {
                            <div class="well well-sm text-center">
                                <img src="@Url.Action("GetImage", "PublicItem", new { id = image.Id })" width="600" alt="Item image"/>
                                <br/>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="well">
        @Html.ActionLink("Back to items list", "ListAllItems", "PublicItem", new { @class = "btn btn-success btn-lg btn-block" })
    </div>

</div>

Auction/Web/Auction.Web/Views/PublicItem/ListAllItems.cshtml
@model IQueryable<global::Auction.Web.ViewModels.Item.ItemViewModel>

@{
    ViewBag.Title = "All Items";
    Layout = "~/Views/Shared/_LayoutGridMvc.cshtml";
}

<h2>@ViewBag.Title</h2>

@if (TempData["Success"] != null)
{
    <div class="row alert alert-success">
        
        @TempData["Success"]
    </div>
}

@Html.Grid(Model).Columns(columns =>
{

    columns.Add()
            .Encoded(false)
            .Sanitized(false)
            .SetWidth(200)
            .RenderValueAs(d =>
                @<b>
                    @if (this.User.IsInRole("Admin"))
                    {
                        @Html.ActionLink("Edit", "Edit", "Item", new { id= d.Id, area = "Admin" }, new { @class = "btn btn-warning" })
                        <span></span>
                        @Html.ActionLink("Delete", "Delete", "Item", new { id= d.Id, area = "Admin" }, new { @class = "btn btn-danger" })

                    }
                @Html.ActionLink("Details", "ItemDetails", "PublicItem", new { id = d.Id }, new { @class = "btn btn-info" })
            </b>);

    columns.Add(i => i.Title).Titled("Title").SetWidth(150);

    columns.Add(i => i.Type).Titled("Type").SetWidth(150);

    columns.Add(i => i.Author).Titled("Author").SetWidth(150);

    columns.Add(i => i.Images.Count).Titled("Number of Images").SetWidth(150);
    
    columns.Add(i => i.CreatedOn).Titled("Created on").SetWidth(150);


}).WithPaging(5).Sortable().Filterable().WithMultipleFilters()